add jobs resource
Pepperi-Addons/papi-sdk pull request #122
Opened 2022-06-16 09:38 UTC by nofarpepperi

2022-06-19 15:41 UTC, Chasky-H commented on entities/addons.ts
> +    ModificationDateTime: string | undefined;
no need fr these since your are extending AddonData

2022-06-19 15:43 UTC, Chasky-H commented on entities/addons.ts
> +    NumberOfTries: number;
Are there any optional fields?

2022-06-19 15:43 UTC, Chasky-H requested changes
Missing version bump

2022-06-20 09:29 UTC, nofarpepperi commented on entities/addons.ts
> +    ModificationDateTime: string | undefined;
fixed

2022-06-20 09:29 UTC, nofarpepperi commented on entities/addons.ts
> +    NumberOfTries: number;
fixed

2022-06-20 09:32 UTC, nofarpepperi commented
> Missing version bump

Oded changing the version also, waiting for his approval

2022-06-21 10:33 UTC, merged