File storage endpoint changes
Pepperi-Addons/papi-sdk pull request #38
Opened 2020-08-12 12:09 UTC by roiaharon-pepperi

added missing endpoint functionality

2020-08-26 09:02 UTC, Chasky-H requested changes

2020-08-26 10:56 UTC, roiaharon-pepperi commented on endpoints/fileStorage.ts
> +export class FileStorageEndpoint extends IterableEndpoint<FileStorage> {
why? the /file_storage endpoint support pagination, you'll need the iter function to go through all the files.

2020-08-26 10:57 UTC, roiaharon-pepperi commented on endpoints/fileStorage.ts
> +export class FileStorageEndpoint extends IterableEndpoint<FileStorage> {
you are right.. my mistake

2020-08-26 10:58 UTC, roiaharon-pepperi commented on endpoints/index.ts
> +export * from './fileStorage';
done

2020-08-26 10:58 UTC, roiaharon-pepperi commented on endpoints/fileStorage.ts
> +    async name(fileName: string): Promise<FileStorage> {
no.. according to api documentation, only /filestorage endpoint support POST

2020-08-26 10:59 UTC, roiaharon-pepperi commented on endpoints/fileStorage.ts
> +        super(service, '/code_jobs');
copy&paste problem.. 👎

2020-09-24 11:23 UTC, Chasky-H approved these changes

2020-09-24 11:23 UTC, merged