Added include owned option to get fields
Pepperi-Addons/papi-sdk pull request #44
Opened 2020-09-06 14:36 UTC by HadarLevi556

Add include_owned option to GET endpoint of fields

2020-09-06 14:52 UTC, Chasky-H commented
These are breaking changes
No can do.

2020-09-07 13:16 UTC, Chasky-H requested changes

2020-09-07 13:16 UTC, Chasky-H commented on endpoints/meta-data.ts
> +    async get(p?: string | { include_owned: boolean }): Promise<ApiFieldObject | ApiFieldObject[] | undefined> {
Why is there undefined in the return value

2020-09-07 13:16 UTC, Chasky-H commented on endpoints/meta-data.ts
> +    async get(p?: string | { include_owned: boolean }): Promise<ApiFieldObject | ApiFieldObject[] | undefined> {
What about default param for include_owned

2020-09-10 09:19 UTC, Chasky-H commented on entities/api-field-object.ts
> +    InternalID: number;
Should be optional if it isn't required in post

2020-09-21 13:08 UTC, Chasky-H requested changes

2020-09-21 13:08 UTC, Chasky-H commented on endpoints/meta-data.ts
> +    async get(params: { include_owned: boolean }): Promise<ApiFieldObject[]>;
Shouldn't this parameter be optional

2020-10-06 12:41 UTC, Chasky-H commented
Something is wrong with the package.json. Why did you install @pepperi-addons/scripts?
Also, you did not bump a version

2020-10-07 07:33 UTC, HadarLevi556 commented
> Something is wrong with the package.json. Why did you install @pepperi-addons/scripts?
> Also, you did not bump a version

Probably by mistake
I did uninstall and upgrade the version

2020-10-07 11:43 UTC, Chasky-H approved these changes

2020-10-07 11:44 UTC, merged