Adal endpoints
Pepperi-Addons/papi-sdk pull request #57
Opened 2021-01-04 11:24 UTC by roiaharon-pepperi

added ADAL endpoint. following changes was made:
1. add 2 interfaces on addon entity file
2. add AddonData class to handle all endpoint logic
3. add 2 optional parameters in papi client constructor
* AddonSecretKey - will be mapped to 'X-Pepperi-SecretKey' header if exist
* ActionUUID - will be mapped to 'X-Pepperi-ActionUUID' header if exist

2021-01-12 10:26 UTC, Chasky-H commented on entities/addons.ts
> +    Type?: 'data' | 'meta_data' | 'elastic';
don't think elastic is supported.

2021-01-12 10:27 UTC, Chasky-H commented on entities/addons.ts
> +    [key: string]: any;
What about:
``` typescript
Key: string
```

2021-01-12 10:33 UTC, Chasky-H requested changes

2021-01-12 10:33 UTC, Chasky-H commented on endpoints/addons.ts
> +    async schemes(body: AddonDataScheme) {
Make this a object, with a post function?
Might need to support GET one day

2021-01-12 10:33 UTC, Chasky-H commented on endpoints/addons.ts
> +    private GetAddonDataUrl(params: any = {}) {
key is optional.

2021-01-12 10:33 UTC, Chasky-H commented on endpoints/addons.ts
> +    async post(body: any = undefined) {
Type should be `AddonData`

2021-01-12 10:33 UTC, Chasky-H commented on endpoints/addons.ts
> +    async schemes(body: AddonDataScheme) {
return type?

2021-01-12 10:33 UTC, Chasky-H commented on endpoints/addons.ts
> +    async get(params: any = {}): Promise<Array<AddonData>> {
return type is implied. no need to specify. I think.

2021-01-12 11:28 UTC, roiaharon-pepperi commented on endpoints/addons.ts
> +    async schemes(body: AddonDataScheme) {
OK

2021-01-12 11:29 UTC, roiaharon-pepperi commented on endpoints/addons.ts
> +    async schemes(body: AddonDataScheme) {
return type should be the same as the type the function recieve, I'll add

2021-01-12 11:31 UTC, roiaharon-pepperi commented on endpoints/addons.ts
> +    async get(params: any = {}): Promise<Array<AddonData>> {
no, It's not implied. because papi_client get method returns any and if we want to support intelisense we need to specify it

2021-01-12 11:33 UTC, roiaharon-pepperi commented on endpoints/addons.ts
> +    async post(body: any = undefined) {
true, I'll change

2021-01-12 11:33 UTC, roiaharon-pepperi commented on endpoints/addons.ts
> +    private GetAddonDataUrl(params: any = {}) {
correct

2021-01-25 09:15 UTC, Chasky-H approved these changes

2021-01-25 09:16 UTC, Chasky-H commented
Don't need the changes to Endpoint.ts but leaving them in anyways.

2021-01-25 09:18 UTC, Chasky-H commented
@roiaharon-pepperi you don't need to bump the version for every change on the same PR.
The only version that will be created is the one when the PR is merged

2021-01-25 09:18 UTC, merged