Adding transaction lines
Pepperi-Addons/papi-sdk pull request #58
Opened 2021-01-05 08:32 UTC by YoniGabe

Adding transaction lines, needed for objects tests

2021-01-06 07:54 UTC, Chasky-H requested changes

2021-01-06 07:54 UTC, Chasky-H commented on entities/transaction_lines.ts
> +    InternalID?: number;
You are missing a bunch of fields.
Also you need to add:
``` typescript
[key: string]: any
```
for TSA's

2021-01-06 07:54 UTC, Chasky-H commented on package-lock.json
> +  "version": "1.18.1",
Should be a minor bump, not a patch. See Readme.

2021-01-06 07:54 UTC, Chasky-H commented on entities/transaction_lines.ts
> +    InternalID?: number;
See `activity.ts`

2021-04-03 19:56 UTC, OrenVilderman commented
Hi, Please remove this, its no longer needed, I added it today, and tomorrow i hope we can marge

2021-04-04 08:41 UTC, closed without merging