NestedObjectData is not always array and Creator is not mandatory whe…
Pepperi-Addons/papi-sdk pull request #68
Opened 2021-04-01 15:42 UTC by OrenVilderman

…n creating Transaction that extends Activity
This fix is needed to writ the PNS tests and remove "as any" from all Yonis tests :(

2021-04-01 15:48 UTC, OrenVildermanPepperi commented
@YoniGabe  please review this fix, i think that with this fix you can improve your code

2021-04-02 15:34 UTC, OrenVildermanPepperi commented
I added 2 new endpoints:
**Items** and **Transaction Lines** and tested them.
I fixed a small bug Alon did when he reverted the code and he added data views probably by mistake since the SDK would not compile without this fix.
I fixed that creator is not mandatory for Activity since Transaction extends Activity and Transaction don't have this field.
I added ImageObject to the base.ts - since this is item that is similar to NestedObjectData as I see it - Please review - @Chasky-H

2021-04-03 18:12 UTC, OrenVildermanPepperi commented
Found that order_by was sent as orderBy - this did not work for me on any endpoint so I changed it for everyone and also changed it in @roiaharon-pepperi in the function that return "ExportApiResponse" please approve this change for me or help me fix it if I miss understood something there

2021-04-03 20:16 UTC, OrenVilderman commented
@Chasky-H  notice that I fixed here what you asked here:
https://github.com/Pepperi-Addons/papi-sdk/pull/58
In January, so you can close that request so it will not confuse us later

2021-04-04 07:01 UTC, Chasky-H requested changes

2021-04-04 07:01 UTC, Chasky-H commented on index.ts
> +export * from './endpoint';
Why are you exporting this?

2021-04-04 07:21 UTC, OrenVilderman commented on index.ts
> +export * from './endpoint';
Since I need to do this:
import { PapiClient, DataView, FindOptions } from '@pepperi-addons/papi-sdk';

Without this export of the endpoint I will have to use the FindOptions that is in the Bin folder

2021-04-04 07:22 UTC, OrenVilderman commented on entities/base.ts
> +    Data?: NestedObjectData[] | NestedObjectData;
Yes this is what I am saying, it was only Array, but I can find it only with singe, but I did not want to introduce a braking change - I am not sure what to do in here...

2021-04-04 07:35 UTC, OrenVilderman commented on entities/activity.ts
> +    Creator?: NestedObject;
Ok my bad, this exist in both Transaction and Activity so in any case what I did it is correct and should stay as it is now

2021-04-04 07:42 UTC, OrenVilderman commented on entities/transaction-lines.ts
> +import { NestedObject } from './base';
Yes all the other fields I see are TSA

2021-04-04 07:44 UTC, OrenVilderman commented on entities/base.ts
> +    Data?: NestedObjectData[] | NestedObjectData;
This was solved on the new patch 1.21.5

2021-04-04 08:05 UTC, Chasky-H commented on index.ts
> +export * from './endpoint';
Then do this:
``` typescript
export { FindOptions } from './endpoint';
```

2021-04-04 08:14 UTC, OrenVilderman commented on index.ts
> +export * from './endpoint';
Done and tested - version 1.21.6

2021-04-04 08:40 UTC, Chasky-H approved these changes

2021-04-04 08:41 UTC, merged