Added async count to Endpoint
Pepperi-Addons/papi-sdk pull request #69
Opened 2021-04-07 13:45 UTC by amirf123

@Chasky-H please see if it can be merged, feel free to fix, but let me know.

2021-04-11 07:08 UTC, Chasky-H requested changes

2021-04-11 07:08 UTC, Chasky-H commented on endpoint.ts
> +        url = query ? url + '&' + query : url;
Should be `?`

2021-04-11 07:08 UTC, Chasky-H commented on endpoint.ts
> +        const query = Endpoint.encodeQueryParams(options);
Suggestion:
Maybe include the `select` query params in the encoding below.
This can be done as follows:
``` typescript
const query = Endpoint.encodeQueryParams({
    select: 'count(InternalID) as count',
    ...options // rest operater flattens into the object
})
```

2021-04-12 08:45 UTC, amirf123 commented on endpoint.ts
> +    async count(options: FindOptions = {}): Promise<number> {
Instead of FindOptions, using an object with just the relevant two options.

2021-04-12 08:45 UTC, amirf123 commented on endpoint.ts
> +        let url = '/Totals';
Using lower-case.

2021-04-12 08:47 UTC, amirf123 commented on endpoint.ts
> +        url = query ? url + '&' + query : url;
No, the '?' is before the 'select'. This might be changed after the suggestion below (include the 'select' query in encoding function).

2021-04-12 09:44 UTC, amirf123 commented on endpoint.ts
> +        const query = Endpoint.encodeQueryParams(options);
Included 'select' query in the encoding.

2021-04-12 10:05 UTC, Chasky-H approved these changes

2021-04-12 10:06 UTC, merged